services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: safetybox
      MYSQL_USER: safetybox
      MYSQL_PASSWORD: change-me
      MYSQL_ROOT_PASSWORD: root-change-me
    ports:
      - "3306:3306"
    volumes:
      - safetybox-mysql:/var/lib/mysql

volumes:
  safetybox-mysql:
